sudo: required

language: node_js

node_js:
  - "8"

before_script:
 - npm install

script: npm run build

cache:
 directories:
   - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master

notifications:
  email: false
